openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'https'
components:
  schemas:
    Personality:
      type: string
      enum:
        - wild
        - calm
        - active
        - benevolent
        - tidy
        - playful
    CatWithPersonalities:
      type: object
      properties:
        species:
          type: string
        personalities:
          type: array
          items:
            $ref: '#/components/schemas/Personality'
