name: Remove old artifacts

on:
  push: {}
  schedule:
    # Every day at 4am
    - cron: '0 2 * * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '2 days'
        skip-tags: true
